services:
  aquario:
    build: .
    container_name: aquario
    hostname: aquario
    environment:
      - PYTHONUNBUFFERED=1 # required to see stdout
    devices:
      - /dev/gpiomem:/dev/gpiomem
    restart: unless-stopped